// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJPM0bF7HtrLMaq95cKTTM0HF4NrxgfE',
    appId: '1:113354293876:web:751f8f635f4ca6f79f0721',
    messagingSenderId: '113354293876',
    projectId: 'dept-ipe',
    authDomain: 'dept-ipe.firebaseapp.com',
    storageBucket: 'dept-ipe.firebasestorage.app',
    measurementId: 'G-QS2J1J2ZLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY5KClRoBm9MTpKH3Bz3OmuuCxlvutEns',
    appId: '1:113354293876:android:becee82fddd01ba79f0721',
    messagingSenderId: '113354293876',
    projectId: 'dept-ipe',
    storageBucket: 'dept-ipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8ia5lgptikWY21B-s8NVhLF9PTY1GAc',
    appId: '1:113354293876:ios:f27684a6244742909f0721',
    messagingSenderId: '113354293876',
    projectId: 'dept-ipe',
    storageBucket: 'dept-ipe.firebasestorage.app',
    iosClientId: '113354293876-891l1ls2asq7i8eqh3p49i3fp7fo9752.apps.googleusercontent.com',
    iosBundleId: 'com.unigrid.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT8ia5lgptikWY21B-s8NVhLF9PTY1GAc',
    appId: '1:113354293876:ios:f27684a6244742909f0721',
    messagingSenderId: '113354293876',
    projectId: 'dept-ipe',
    storageBucket: 'dept-ipe.firebasestorage.app',
    iosClientId: '113354293876-891l1ls2asq7i8eqh3p49i3fp7fo9752.apps.googleusercontent.com',
    iosBundleId: 'com.unigrid.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKJPM0bF7HtrLMaq95cKTTM0HF4NrxgfE',
    appId: '1:113354293876:web:10d6150cf4a01fd29f0721',
    messagingSenderId: '113354293876',
    projectId: 'dept-ipe',
    authDomain: 'dept-ipe.firebaseapp.com',
    storageBucket: 'dept-ipe.firebasestorage.app',
    measurementId: 'G-GXC6DGMJGY',
  );
}
